### ISSUE TITLE
Window dimensions 

### ISSUE THREAD

**Issue by posfan12** [Jeremy1980/LDBoxer#1]
In Windows 7, and probably other versions of Windows, the program's panels are hidden when using larger size text in the Operating System. Go to:

Control Panel\Appearance and Personalization\Display

I have the text size set to Medium - 125%. This causes the program to become unusable.

**Comment by Jeremy1980** [comment]
If you use **cmd.exe** **,** then console setting is independent **.** Read this article http://www.wikihow.com/Customize-the-Font-in-Windows-Command-Prompt and go back if you have still question.

**Comment by posfan12** [comment]
But LDBoxer is a GUI app. Why would console text size matter?

**Comment by Jeremy1980** [comment]
I you talk about version from sourceforge.net created by Tore Eriksson.  Yes it have GUI. But as answer to this question https://forums.ldraw.org/thread-21733.html. I Create console version. You must consider what you have using ?
