### ISSUE TITLE
Working version

### ISSUE THREAD

**Issue by posfan12** [Jeremy1980/LDBoxer#5]
I got the script working I think. Here is the new version:

[LDBoxer_mjh_20180124.zip](https://github.com/Jeremy1980/LDBoxer/files/1662352/LDBoxer_mjh_20180124.zip)

**Comment by posfan12** [comment]
Someone could probably optimize the script better.

**Comment by Jeremy1980** [comment]
Thanks for your time.

**Comment by posfan12** [comment]
I updated the script to print progress info while it is running. I also tested the script on Datsville, and it is *much* slower than I remember Tore Eriksson's Pascal version being, despite a few optimizations that I added. I will try to speed things up even more when I get the chance.

[LDBoxer_mjh_20180125.zip](https://github.com/Jeremy1980/LDBoxer/files/1666193/LDBoxer_mjh_20180125.zip)

**Comment by posfan12** [comment]
This version is better optimized. I have eliminated one "pass" of all parts. There are now two "passes" instead of three. Not sure if I can make further optimizations.

[LDBoxer_mjh_20180126.zip](https://github.com/Jeremy1980/LDBoxer/files/1666675/LDBoxer_mjh_20180126.zip)

**Comment by posfan12** [comment]
This version is better optimized. I have eliminated one "pass" of all parts. There are now two "passes" instead of three. Not sure if I can make further optimizations.

[LDBoxer_mjh_20180126.zip](https://github.com/Jeremy1980/LDBoxer/files/1666753/LDBoxer_mjh_20180126.zip)

**Comment by posfan12** [comment]
This new version should trim all zeros to the right of the decimal point, and should reduce model file size considerably.

Note that if you use PyPy instead of CPython to run the script, the performance is actually very good. I was able to process Datsville in under 3 hours, compared to about 24 hours for the original Pascal program.

[LDBoxer_mjh_20180127.zip](https://github.com/Jeremy1980/LDBoxer/files/1669905/LDBoxer_mjh_20180127.zip)
